/*
 * Workload Identity Federation (W.I.F.) Configuration
 *
 * Defined here is the API for management of WIF Configuration for Openshift Dedicated on Google Cloud Platform (OSD-GCP).
 *
 * API version: 0.0.0
 * Contact: rcampos@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type WifConfigInput struct {
	DisplayName string `json:"display_name"`
	ProjectId   string `json:"project_id"`
}
