/*
 * Workload Identity Federation (W.I.F.) Configuration
 *
 * Defined here is the API for management of WIF Configuration for Openshift Dedicated on Google Cloud Platform (OSD-GCP).
 *
 * API version: 0.0.0
 * Contact: rcampos@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import (
	"encoding/json"
	"fmt"
)

type WifConfigOutput struct {
	Metadata *WifConfigMetadata `json:"metadata,omitempty"`
	Spec     *WifConfigInput    `json:"spec,omitempty"`
	Status   *WifConfigStatus   `json:"status,omitempty"`
}

type WifConfigOutputList struct {
	Items []WifConfigOutput `json:"items"`
}

func WifConfigOutputFromJson(rawWifConfigOutput []byte) (WifConfigOutput, error) {
	var output WifConfigOutput
	err := json.Unmarshal(rawWifConfigOutput, &output)
	return output, err
}

func WifConfigOutputListFromJson(data []byte) (*WifConfigOutputList, error) {
	var wifConfigListOutput WifConfigOutputList
	err := json.Unmarshal(data, &wifConfigListOutput)
	if err != nil {
		return nil, fmt.Errorf("error unmarshalling data: %v", err)
	}
	return &wifConfigListOutput, nil

}
